### ISSUE TITLE
ingest endpoint not found with curl

### ISSUE THREAD

**Issue by danielw97** [CubicalBatch/deaddit#1]
Hi,
I've recently tried to spin this project up locally, although when trying to load the subdedits base json I receive an errror that the /ingest endpoint doesn't exist with a 404.
Is there something I have to do to enable this functionality?
Thanks in advance.

**Comment by cubicalbatch** [comment]
Sorry - I moved it to /api/ingest and forgot to update the README. I've updated it now.

Use http://localhost:5000/api/ingest and it should work
