### ISSUE TITLE
curl command problem

### ISSUE THREAD

**Issue by scalar27** [CubicalBatch/deaddit#3]
Kind of a newbie, but when I try the curl command:
curl -X POST -H "Content-Type: application/json" -d "@deaddit/data/subdeaddits_base.json" http://localhost:5000/api/ingest

nothing seems to happen.  When I try it with -v (verbose):
curl -X POST -H "Content-Type: application/json" -d "@deaddit/data/subdeaddits_base.json" http://localhost:5000/api/ingest -v

I get:
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying [::1]:5000...
* Connected to localhost (::1) port 5000
> POST /api/ingest HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/8.4.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 5697
> 
< HTTP/1.1 404 Not Found
< Content-Length: 0
< Server: AirTunes/695.5.1
< 
* Connection #0 to host localhost left intact

Any suggestions?

**Comment by cubicalbatch** [comment]
Hi! It looks like you have something else running on port 5000 (Airtunes).
You can either turn that off, or change the app.py to use another port

```
if __name__ == ‘__main__’:
   app.run(debug=True, port=port_number)
```

Then, after starting the app, change the loader.py to point to that port instead of 5000
